from myapp.views.Level.level1 import *
from myapp.views.Level.level2 import *
from myapp.views.Level.level3 import *
from myapp.views.Level.level4 import *
from myapp.views.Level.level5 import *
from myapp.views.Level.level6 import *
from myapp.views.Level.level7 import *
from myapp.views.Level.level8 import *
from myapp.views.Level.level9 import *
from myapp.views.Level.level9 import *
from myapp.views.Level.level10 import *
