# Generated by Django 2.0.12 on 2019-03-20 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='total_time_taken',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
