# Generated by Django 2.0.12 on 2019-03-21 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190320_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='userquestion',
            name='time_taken',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
