# Generated by Django 2.1.7 on 2019-04-05 17:29

from django.db import migrations, models
import myapp.models.schema_file


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190328_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.CharField(default=myapp.models.schema_file._generate_unique_uri, max_length=100),
        ),
    ]
