# Generated by Django 2.0.12 on 2019-04-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190406_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
