# Generated by Django 2.0.12 on 2019-04-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190407_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubmission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='answer',
            field=models.CharField(max_length=1000),
        ),
    ]
